### PR TITLE
VAULT-5038 Support release/vault-* branches for releases

### PR DESCRIPTION
**Pull request by swenson**
# Overview
Updating the release process to work from the release branches as well.

# Design of Change
Needed for CRT tooling

# Related Issues/Pull Requests
[x] [PR #75](https://github.com/hashicorp/vault-plugin-database-oracle/pull/75)

# Contributor Checklist
[x] Add relevant docs to upstream Vault repository, or sufficient reasoning why docs won’t be added yet
[x] Add output for any tests not ran in CI to the PR description (eg, acceptance tests)
[x] Backwards compatible

### CODE REVIEW

**Review by fairclothjm — APPROVED** [review]
LGTM, thanks!

**Comment by swenson** [comment]
(I'll test wildcards separately. I'll merge once tests pass.)

**Review by calvn — APPROVED** [review]
Looks good. Does the branch support globbing so we don't have to keep updating on every release branch cut?

**Comment by swenson** [comment]
Testing that now @calvn

**Comment by swenson** [comment]
Thanks!

**Pull request merged**
