### PR TITLE
Kill sessions in a RAC aware manner.

### PR DESCRIPTION
**Pull request by vt-ms**
Uses GV$SESSION to get cluster-wide view of sessions and uses the returned instance id to kill sessions across nodes.

Suggests resolution to issue #30

### CODE REVIEW

**Comment by pcman312** [comment]
Hi @vt-ms ! I'm really sorry for not responding to this earlier. I wanted to give you an update on the efforts we've had around this.

This looks good & straightforward, however we haven't been able to test it with a real RAC database cluster. We've tried several times to get access to or set up a cluster but have been unsuccessful each time. I want to assure you this hasn't been forgotten, we just don't have the ability to test this fix effectively.

**Comment by MarkDeckert** [comment]
Guys, is this the right approach?  The whole point of having a custom revocation_statement is so that the query can be customized per environment.

Take the postgres and mysql plugins for example, unlike the Oracle plugin, do not have explicit disconnect statements that run every time regardless of revocation_statement.  They only run the default disconnect/revoke queries if there is no revoke statement at all.

If the disconnect query is instead conditional on whether there is a custom revoke or not, then you won't need a real RAC db cluster to test on. The user can just add whatever disconnect query they want, right in the revoke statement.

I'm currently having an issue right now where I need to run a custom disconnect and I can't without forking the plugin.  It would solve both issues (mine and this) if disconnect was conditional on revoke being customized.

**Review by NicoleS021 — APPROVED** [review]

**Review by NicoleS021 — APPROVED** [review]

**Comment by vt-ms** [comment]
@MarkDeckert I think that's a good idea. If the plugin user could optionally name their own plsql procedure or maybe even an anonymous block for handling revoke (and disconnect) logic then the plugin could just use the existing single instance logic as the default and transfer the risk of a more complicated testing environment to the user. 

As you probably know, the disconnect logic is important to do before running a `drop user` statement else the operation could fail with [ORA-01940](https://docs.oracle.com/en/database/oracle/oracle-database/19/errmg/ORA-01500.html#GUID-65B2B9E5-7075-4D53-91B8-FCAECA0AEE0E). In fact, I think I 'd almost like to see the account get expired and locked before the disconnect and drop operations run.

**Comment by MarkDeckert** [comment]
@vt-ms I think we are of the same thought.  In fact in our environment we do similar to what you are proposing in your last sentence, since we can't afford to simply disconnect the active session and risk causing some application transaction failure.  We need to know why an account still has an active session before just killing it.  So the process is:

1. Lock account via custom revocation_statement
2. Clean up/drop later at DBAs leisure (usually an automated process on the oracle side)

In order to do this though we use a modified version of the plugin.  Our forked version still runs the disconnect but _only_ if there is _no_ custom_revocation.  Since oracle does actually require disconnect before drop as you mentioned.

**Comment by vt-ms** [comment]
@pcman312 What do you think about this change in direction suggested by @MarkDeckert to make the disconnect logic conditional on the absence of any custom revocation statements. With this approach one could then put RAC disconnect logic into a stored procedure and execute that via a custom revocation statement.

I think one downside is that any plugin users who are currently adding custom revocation statements are probably counting on the plugin to do the disconnect, so they would potentially face ORA-01940 on drop unless they updated their revocation code to do the disconnects.

**Comment by pcman312** [comment]
@vt-ms I think in principle it's the right direction, however as you said backwards compatibility would need to be resolved. I managed to create a set of SQL statements that can be used in place of the `disconnectSession` logic which could be used as part of the default revocation statements. Unfortunately when the plugin goes to execute statements, it splits those statements on `;` regardless of how they are configured ([example](https://github.com/hashicorp/vault-plugin-database-oracle/blob/master/oracle.go#L262)). This allows users to do things like `vault write database/roles/oraclerole creation_statements='STATEMENT1; STATEMENT2; STATEMENT3;'` and Vault will automatically split those into three separate statements. However, the statements that can be used to replace `disconnectSession` need to retain some of the semi-colons. We could get around this particular issue with a config parameter that basically says whether or not the statements should be split on semi-colons, but then we still have the question of `disconnectSession`. As you said, if we remove it that will break some existing users because they have custom revocation statements and are expecting the plugin to disconnect any open sessions.

Unfortunately I haven't found a design that both retains backwards compatibility and solve this problem yet. We are having discussions around improving this plugin so it hasn't been forgotten. Until recently it was a lower priority than a number of other projects, but we have started looking into it more recently.

**Comment by vt-ms** [comment]
@pcman312 One way to get around splitting on `;` could be to just put all the logic into a stored procedure and use `revocation_statements="CALL vault_revoke_proc('{{username}}');` rather than using an anonymous pl/sql block e.g., `begin ... some statement; ... end;`

**Comment by pcman312** [comment]
Closing this PR in favor of #62 which was just merged. It won't be released today, but will during our next release cadence for this plugin (in a couple of weeks).

**Pull request closed without merging**
